@startuml

title __UTIL's Class Diagram__\n

  namespace com.tracker {
    namespace util {
      class com.tracker.util.Constants {
          {static} + API_KEY : String
          {static} + API_KEY_STRING : String
          {static} + BASE_URL : String
          {static} + BASE_URL_IMAGES_BACK : String
          {static} + BASE_URL_IMAGES_NETWORK : String
          {static} + BASE_URL_IMAGES_PORTRAIT : String
          {static} + BASE_URL_IMAGES_POSTER : String
          {static} + BASE_URL_IMDB : String
          {static} + BASE_URL_INSTAGRAM : String
          {static} + BASE_URL_TWITTER : String
          {static} + BASE_URL_WEB : String
          {static} + BASE_URL_YOUTUBE : String
          {static} + EN : String
          {static} + ES : String
          {static} + GENRE : String
          {static} + GET_PEOPLE_API_EXTRAS : String
          {static} + GET_SERIE_API_EXTRAS : String
          {static} + ID : String
          {static} + ID_ACTOR : String
          {static} + ID_SEASON : String
          {static} + ID_SERIE : String
          {static} + NETWORKS : String
          {static} + POP_DESC : String
          {static} + TRAILER : String
          {static} + URL_WEBVIEW : String
          - Constants()
      }
    }
  }
  

  namespace com.tracker {
    namespace util {
      class com.tracker.util.Util {
          {static} + checkNull()
          {static} + getImage()
          {static} + getImageNoPlaceholder()
          {static} + getImagePortrait()
          {static} + getLanguage()
          - Util()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
